all: pilha.o selection.o
	gcc pilha.o selection.o -o c -Wall -Wextra -Werror -pedantic -std=c99 -g

pilha.c:
	gcc -c pilha.c -Wall -Wextra -Werror -pedantic -std=c99 

selection.c:
	gcc -c selection.c -Wall -Wextra -Werror -pedantic -std=c99 

clean:
	rm *.o c
